Solution
mate-academy/py-taxi-service-class-based-views pull request #103
Opened 2022-10-26 18:17 UTC by StasOkhrym

<img width="1281" alt="Screenshot 2022-10-26 210412" src="https://user-images.githubusercontent.com/105078166/198104786-5bff125a-97d0-4f3c-af25-872ae85d2231.png">
<img width="1280" alt="Screenshot 2022-10-26 210450" src="https://user-images.githubusercontent.com/105078166/198104790-e6056b59-6fb3-4cd2-841d-db7fe2f03aa5.png">
<img width="1280" alt="Screenshot 2022-10-26 210516" src="https://user-images.githubusercontent.com/105078166/198104793-f0fe32d6-295d-4fa2-b223-50e22a5933b4.png">
<img width="1280" alt="Screenshot 2022-10-26 210649" src="https://user-images.githubusercontent.com/105078166/198104798-fd62872e-60f6-4db4-abbb-ea938efc6fc4.png">
<img width="1280" alt="Screenshot 2022-10-26 210841" src="https://user-images.githubusercontent.com/105078166/198104801-a7f27176-35d6-44db-bb0e-952256cf8322.png">
<img width="1280" alt="Screenshot 2022-10-26 210557" src="https://user-images.githubusercontent.com/105078166/198104805-ccac69a5-2e71-4804-a6c5-e88fe0295420.png">

2022-10-26 18:42 UTC, mltdll requested changes
Looks good. At least the code part.

2022-10-26 18:42 UTC, mltdll commented on static/css/styles.css
> +What do I feel here
Beautiful. Why didn't you include it in your website?

2022-10-26 18:42 UTC, mltdll commented on templates/taxi/car_detail.html
> +    <p><strong>No one drive this car.</strong></p>
You mean, no one drives?

2022-10-26 18:42 UTC, mltdll commented on templates/taxi/car_list.html
> +    <p>There no cars in list</p>
There **are** no cars. By the way, you forgot the period at the end of the sentence.

2022-10-26 18:42 UTC, mltdll commented on templates/taxi/driver_list.html
> +      <div>It looks like nobody works here</div>
Where did the `.` go?

2022-10-26 18:42 UTC, mltdll commented on templates/taxi/manufacturer_list.html
> +    <p>There are no manufacturers</p>
50% of the messages about empty stuff in your website seem to end with period, 50% don't. Does that mean you're in superposition?

2022-10-26 18:52 UTC, mltdll approved these changes

2022-10-27 17:03 UTC, Nattalli requested changes

2022-10-27 17:21 UTC, StasOkhrym commented
<img width="1280" alt="Screenshot 2022-10-27 201945" src="https://user-images.githubusercontent.com/105078166/198357029-0a92fa53-4ea7-4c98-9aad-45dc2d03f85f.png">
It should be like this?

2022-10-27 19:36 UTC, Nattalli commented
> <img alt="Screenshot 2022-10-27 201945" width="1280" src="https://user-images.githubusercontent.com/105078166/198357029-0a92fa53-4ea7-4c98-9aad-45dc2d03f85f.png">
> 
> It should be like this?

yes, kind of

2022-10-27 19:36 UTC, Nattalli approved these changes

2024-06-03 10:54 UTC, closed without merging