soluiton/develop
mate-academy/py-taxi-service-class-based-views pull request #532
Opened 2024-01-08 15:44 UTC by sbilikepy

2024-01-08 15:46 UTC, sbilikepy commented
Home page
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/109094572/16e1a8c1-756f-4aa8-af6f-e35b60c39a83)

2024-01-08 15:47 UTC, sbilikepy commented
Manufacturers![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/109094572/e82f83c5-87e8-428e-b806-91df5e53188f)

2024-01-08 15:47 UTC, sbilikepy commented
Cars
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/109094572/7c9d6768-364f-4d7f-baae-29a04ac022c0)

2024-01-08 15:47 UTC, sbilikepy commented
Drivers
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/109094572/47889497-449a-4ff3-b6fc-7fa7b7cf375d)

2024-01-08 15:48 UTC, sbilikepy commented
/cars/pk
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/109094572/37b0f3e7-f2b7-43b5-8d63-9cd10be9de27)

2024-01-08 15:49 UTC, sbilikepy commented
/drivers/pk
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/109094572/322ff350-54ab-4a32-a4d0-eaef421f9d9a)

2024-01-09 14:49 UTC, vsmutok requested changes

2024-01-09 14:49 UTC, vsmutok commented on templates/taxi/car_detail.html
> +{% endblock %}
add new empty line

2024-01-09 14:49 UTC, vsmutok commented on templates/includes/pagination.html
> +{% endif %}
add new empty line

2024-01-09 14:49 UTC, vsmutok commented on taxi/urls.py
> +    path("drivers/<int:pk>", DriverDetailView.as_view(), name="driver-detail"),
```suggestion
    path("drivers/<int:pk>/", DriverDetailView.as_view(), name="driver-detail"),
```

2024-01-09 14:49 UTC, vsmutok commented on .gitignore
> +GitHub.sublime-settings
add new empty line

2024-01-09 14:49 UTC, vsmutok commented on taxi/models.py
> +        ordering = ["name"]  # 1.2
`1.2` What does this comment mean?

2024-01-09 15:12 UTC, sbilikepy commented on taxi/models.py
> +        ordering = ["name"]  # 1.2
oh it was my personal notes for readme tracking, my bad

2024-01-09 15:13 UTC, sbilikepy commented
ordering has been added to prevent pagination issues
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/109094572/35cad589-3e74-43c8-b247-211dafa21021)

2024-01-09 17:05 UTC, ArsenPidhoretskyi approved these changes
Well done!

2026-07-30 15:20 UTC, closed without merging