Done
mate-academy/py-taxi-service-class-based-views pull request #545
Opened 2024-01-17 14:57 UTC by VladyslavShepilov

2024-01-17 14:57 UTC, VladyslavShepilov commented
<img width="1512" alt="Снимок экрана 2024-01-17 в 16 55 35" src="https://github.com/mate-academy/py-taxi-service-class-based-views/assets/136336159/f0836b78-d6b3-4c32-a4d6-27306872012b">
<img width="1512" alt="Снимок экрана 2024-01-17 в 16 55 40" src="https://github.com/mate-academy/py-taxi-service-class-based-views/assets/136336159/fa9137f7-00e5-461e-b425-ca105a44d298">
<img width="1512" alt="Снимок экрана 2024-01-17 в 16 55 47" src="https://github.com/mate-academy/py-taxi-service-class-based-views/assets/136336159/ab00221b-fc25-4130-83c4-5724f45d990c">
<img width="1512" alt="Снимок экрана 2024-01-17 в 16 55 53" src="https://github.com/mate-academy/py-taxi-service-class-based-views/assets/136336159/556ee452-6b57-467a-bc84-d82f3307f6ff">
<img width="1512" alt="Снимок экрана 2024-01-17 в 16 55 57" src="https://github.com/mate-academy/py-taxi-service-class-based-views/assets/136336159/a29d83f3-5df0-4101-8436-bbc26628a04a">
<img width="1512" alt="Снимок экрана 2024-01-17 в 16 56 32" src="https://github.com/mate-academy/py-taxi-service-class-based-views/assets/136336159/0c07632b-98b5-4405-8efe-c256d60aed0d">
<img width="1512" alt="Снимок экрана 2024-01-17 в 16 56 42" src="https://github.com/mate-academy/py-taxi-service-class-based-views/assets/136336159/03be6e94-b262-4a83-a647-d7005aec4d0e">

2024-01-17 14:59 UTC, vasylhnatiuk requested changes

2024-01-17 14:59 UTC, vasylhnatiuk commented on templates/includes/pagination.html
> +{% endif %}
add newline

2024-01-17 14:59 UTC, vasylhnatiuk commented on templates/taxi/manufacturer_list.html
> +{% endblock %}
add newline

2024-01-17 17:45 UTC, vsmutok requested changes

2024-01-17 17:45 UTC, vsmutok commented on taxi/urls.py
> +    DriverListView, DriverDetailView
```suggestion
from .views import (
    index,
    ManufacturerListView,
    CarListView,
    CarDetailView,
    DriverListView,
    DriverDetailView
)
```

2024-01-18 09:57 UTC, ArsenPidhoretskyi approved these changes
Well done!

2025-10-24 20:36 UTC, closed without merging