finished task
mate-academy/py-taxi-service-class-based-views pull request #548
Opened 2024-01-21 13:36 UTC by BGBroth

by-manufacturers/
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/135819754/c7091c17-5b00-4506-a727-bd60b5c66613)
cars/
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/135819754/2d250225-5359-4cbd-ba9d-45d40d8cfc22)
cars/1/
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/135819754/ef497307-084c-4f42-bfde-42eb8fc16d9e)
drivers/
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/135819754/deb74439-da4c-49a5-89a9-f502ec5f7a76)
drivers/3/
![image](https://github.com/mate-academy/py-taxi-service-class-based-views/assets/135819754/74a5c533-1898-4052-98af-2e5f227146bf)

2024-01-21 15:00 UTC, viktoria-rybenchuk requested changes

2024-01-21 15:00 UTC, viktoria-rybenchuk commented on taxi/urls.py
> +from .views import (
use absolute imports instead of relative

2024-01-21 15:00 UTC, viktoria-rybenchuk commented on taxi/views.py
> +    template_name = "taxi/manufacturer_list.html"
Do you really need override template name?

2024-01-21 15:00 UTC, viktoria-rybenchuk commented on taxi/views.py
> +    template_name = "taxi/car_list.html"
the same here

2024-01-21 15:00 UTC, viktoria-rybenchuk commented on taxi/views.py
> +    template_name = "taxi/car_list.html"
Fix in all places

2024-01-27 11:24 UTC, pavlejviki approved these changes
Good job

2024-07-09 09:00 UTC, closed without merging