New develop
mate-academy/py-taxi-service-class-based-views pull request #787
Opened 2024-09-09 14:03 UTC by onyevyerov

2024-09-09 14:03 UTC, onyevyerov commented
![image_2024-09-09_15-48-49](https://github.com/user-attachments/assets/9852cc83-f14f-4e1a-87af-a915de5c8062)
![image_2024-09-09_15-56-47](https://github.com/user-attachments/assets/4a52392f-41a6-43b2-8a0e-ae82a74383ad)
![image_2024-09-09_15-48-49 (2)](https://github.com/user-attachments/assets/8d05bbc2-ca86-439b-a16d-4669b6b7cb7f)
![image_2024-09-09_15-48-49 (3)](https://github.com/user-attachments/assets/b8ca4d3d-76a6-4f09-b2fe-5355980e3353)
![image_2024-09-09_15-48-49 (4)](https://github.com/user-attachments/assets/a3a8772d-a087-40b1-854c-3d660d35dab4)
![image_2024-09-09_15-48-49 (5)](https://github.com/user-attachments/assets/f95c73bb-15df-4710-89fa-e6219c3bc1c6)

2024-09-09 14:13 UTC, LLkaia requested changes

2024-09-09 14:13 UTC, LLkaia commented on taxi/urls.py
> +                    CarDetailView, DriverListView, DriverDetailView)
Use absolute imports only

2024-09-09 14:13 UTC, LLkaia commented on taxi/urls.py
> +
Remove redundant blank line

2024-09-09 14:13 UTC, LLkaia commented on taxi/views.py
> +    queryset = Manufacturer.objects.all().order_by("name")
all() is redundant

2024-09-09 14:13 UTC, LLkaia commented on templates/taxi/car_detail.html
> +
blank line is redundant

2024-09-09 14:13 UTC, LLkaia commented on taxi/urls.py
> +                    CarDetailView, DriverListView, DriverDetailView)
And place one item per one line

2024-09-09 16:53 UTC, Dimosphen1 requested changes
Several minor changes were requested

2024-09-09 16:53 UTC, Dimosphen1 commented on taxi/urls.py
> +                        DriverDetailView)
Place each import on a new line so that there would be no imports on the same line with opening and closing parenthesis

2024-09-10 05:26 UTC, vsmutok approved these changes
Looks Good!

2026-04-10 13:09 UTC, closed without merging